import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="h-16 bg-green-300 px-4 flex items-center">
          <form action="/items" className="max-w-screen-lg m-auto flex-1 flex">
            <Link href='/' className="mr-4">Interview Test - Search for a product</Link>
            <input type="text" name='search' className="h-8 flex-1 px-5"/>
            <button className="bg-gray-300 px-4 py-1 text-slate-400" type="submit">Search</button>
          </form>
        </header>
        <h2>THE API WILL BRING 4 ITEMS THAT YOU SEARCH</h2>
        <main className="max-w-screen-xl p-4">
          {children}
        </main>
      </body>
    </html>
  );
}
